### ISSUE TITLE
无法自动更新

### ISSUE THREAD

**Issue by madlifer** [ddgth/cf2dns#1]
环境  ubuntu20.04LTS python3 
原脚本没变，加了两个print，确认AKID跟密码没错

回显错误如下：

`b'{"key": "o1zrmHAF"}'
{'code': 200, 'info': [{'colo': 'FRA', 'ip': '104.20.55.231', 'latency': 207, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 2443, 'time': '2020-10-05 18:20:41'}, {'colo': 'FRA', 'ip': '104.20.53.252', 'latency': 204, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 679, 'time': '2020-10-05 18:20:20'}, {'colo': 'LAX', 'ip': '104.27.196.160', 'latency': 157, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 634, 'time': '2020-10-06 03:20:05'}, {'colo': 'LAX', 'ip': '104.27.202.98', 'latency': 166, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 490, 'time': '2020-10-06 04:20:21'}, {'colo': 'LAX', 'ip': '104.27.199.139', 'latency': 196, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 430, 'time': '2020-10-05 12:05:00'}, {'colo': 'SJC', 'ip': '172.67.66.59', 'latency': 149, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3151, 'time': '2020-10-06 07:46:59'}, {'colo': 'SJC', 'ip': '104.26.11.247', 'latency': 153, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3150, 'time': '2020-10-06 07:47:12'}, {'colo': 'SJC', 'ip': '172.67.3.114', 'latency': 156, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3149, 'time': '2020-10-06 07:47:19'}, {'colo': 'SJC', 'ip': '172.67.66.50', 'latency': 150, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3149, 'time': '2020-10-06 07:47:05'}, {'colo': 'FRA', 'ip': '172.67.17.70', 'latency': 159, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3148, 'time': '2020-10-06 07:47:25'}, {'colo': 'LAX', 'ip': '104.27.105.75', 'latency': 206, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 3149, 'time': '2020-10-05 16:11:07'}, {'colo': 'LAX', 'ip': '104.27.108.145', 'latency': 211, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 3149, 'time': '2020-10-05 13:26:03'}, {'colo': 'LAX', 'ip': '104.25.130.154', 'latency': 209, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 3148, 'time': '2020-10-05 15:10:25'}, {'colo': 'LAX', 'ip': '104.27.108.114', 'latency': 203, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 2048, 'time': '2020-10-05 18:10:56'}, {'colo': 'LAX', 'ip': '104.27.70.102', 'latency': 215, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 978, 'time': '2020-10-05 14:10:48'}], 'total': 15}
2020-10-06 01:51:55,087 - cf1dns.py[line:183] - ERROR: CHANGE DNS ERROR: ----Time: 2020-10-06 01:51:55----MESSAGE: list indices must be integers or slices, not str
`

**Comment by ddgth** [comment]
麻烦你把源代码151行下加一行
print(ret)
看下输出

**Comment by madlifer** [comment]
加了之后似乎无回显，输出如下：

b'{"key": "o1zrmHAF"}'
{'code': 200, 'info': [{'colo': 'FRA', 'ip': '104.20.62.6', 'latency': 175, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 3151, 'time': '2020-10-07 05:05:46'}, {'colo': 'FRA', 'ip': '104.20.53.85', 'latency': 173, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 3151, 'time': '2020-10-07 05:05:33'}, {'colo': 'FRA', 'ip': '104.20.60.247', 'latency': 171, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 3151, 'time': '2020-10-07 05:05:20'}, {'colo': 'FRA', 'ip': '104.20.55.231', 'latency': 173, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 3148, 'time': '2020-10-07 05:05:27'}, {'colo': 'SJC', 'ip': '104.26.11.186', 'latency': 148, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 404, 'time': '2020-10-07 03:05:12'}, {'colo': 'SEA', 'ip': '104.27.100.240', 'latency': 184, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3152, 'time': '2020-10-07 11:02:56'}, {'colo': 'SEA', 'ip': '104.27.110.234', 'latency': 185, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3148, 'time': '2020-10-07 11:03:02'}, {'colo': 'SEA', 'ip': '104.25.141.45', 'latency': 183, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3147, 'time': '2020-10-07 11:17:58'}, {'colo': 'FRA', 'ip': '172.67.63.9', 'latency': 206, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3147, 'time': '2020-10-07 10:02:01'}, {'colo': 'FRA', 'ip': '104.27.192.253', 'latency': 210, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 2263, 'time': '2020-10-07 10:02:26'}, {'colo': 'FRA', 'ip': '104.25.120.168', 'latency': 177, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 948, 'time': '2020-10-06 12:10:33'}, {'colo': 'LAX', 'ip': '104.27.193.137', 'latency': 205, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 654, 'time': '2020-10-06 14:25:34'}, {'colo': 'FRA', 'ip': '104.27.11.177', 'latency': 191, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 637, 'time': '2020-10-06 11:25:53'}, {'colo': 'LHR', 'ip': '104.25.115.182', 'latency': 192, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 581, 'time': '2020-10-06 11:26:00'}, {'colo': 'AMS', 'ip': '104.24.232.173', 'latency': 193, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 515, 'time': '2020-10-06 11:26:11'}], 'total': 15}
2020-10-07 03:54:59,767 - cf1dns.py[line:184] - ERROR: CHANGE DNS ERROR: ----Time: 2020-10-07 03:54:59----MESSAGE: list indices must be integers or slices, not str

**Comment by ddgth** [comment]
> 加了之后似乎无回显，输出如下：
> 
> b'{"key": "o1zrmHAF"}'
> {'code': 200, 'info': [{'colo': 'FRA', 'ip': '104.20.62.6', 'latency': 175, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 3151, 'time': '2020-10-07 05:05:46'}, {'colo': 'FRA', 'ip': '104.20.53.85', 'latency': 173, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 3151, 'time': '2020-10-07 05:05:33'}, {'colo': 'FRA', 'ip': '104.20.60.247', 'latency': 171, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 3151, 'time': '2020-10-07 05:05:20'}, {'colo': 'FRA', 'ip': '104.20.55.231', 'latency': 173, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 3148, 'time': '2020-10-07 05:05:27'}, {'colo': 'SJC', 'ip': '104.26.11.186', 'latency': 148, 'line': 'CM', 'loss': 0, 'node': 'ZJBGP', 'speed': 404, 'time': '2020-10-07 03:05:12'}, {'colo': 'SEA', 'ip': '104.27.100.240', 'latency': 184, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3152, 'time': '2020-10-07 11:02:56'}, {'colo': 'SEA', 'ip': '104.27.110.234', 'latency': 185, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3148, 'time': '2020-10-07 11:03:02'}, {'colo': 'SEA', 'ip': '104.25.141.45', 'latency': 183, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3147, 'time': '2020-10-07 11:17:58'}, {'colo': 'FRA', 'ip': '172.67.63.9', 'latency': 206, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 3147, 'time': '2020-10-07 10:02:01'}, {'colo': 'FRA', 'ip': '104.27.192.253', 'latency': 210, 'line': 'CU', 'loss': 0, 'node': 'ZJBGP', 'speed': 2263, 'time': '2020-10-07 10:02:26'}, {'colo': 'FRA', 'ip': '104.25.120.168', 'latency': 177, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 948, 'time': '2020-10-06 12:10:33'}, {'colo': 'LAX', 'ip': '104.27.193.137', 'latency': 205, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 654, 'time': '2020-10-06 14:25:34'}, {'colo': 'FRA', 'ip': '104.27.11.177', 'latency': 191, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 637, 'time': '2020-10-06 11:25:53'}, {'colo': 'LHR', 'ip': '104.25.115.182', 'latency': 192, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 581, 'time': '2020-10-06 11:26:00'}, {'colo': 'AMS', 'ip': '104.24.232.173', 'latency': 193, 'line': 'CT', 'loss': 0, 'node': 'ZJBGP', 'speed': 515, 'time': '2020-10-06 11:26:11'}], 'total': 15}
> 2020-10-07 03:54:59,767 - cf1dns.py[line:184] - ERROR: CHANGE DNS ERROR: ----Time: 2020-10-07 03:54:59----MESSAGE: list indices must be integers or slices, not str

已修复 请再试一次
