### ISSUE TITLE
筛选带宽建议

### ISSUE THREAD

**Issue by qiuzi** [ddgth/cf2dns#10]
广东电信地区 测试了2天感觉筛选机制有欠妥，主要在于带宽不稳定，建议增加延迟与带宽区分选项，可以满足低延迟低带宽  高延迟高带宽使用环境 默认带宽满足20M就更好了

**Comment by ddgth** [comment]
最早的版本是每个运营商筛选10个最优IP  根据下载速度排序 选择最靠前的几个IP 但是如果每个使用者都使用前几个 那么就会造成阻塞 所以目前的版本是每个运营商筛选10个最优IP 然后随机选择  如果你想试试之前的版本 可以看看commit log

**Comment by qiuzi** [comment]
要不就把筛选范围适量扩大 但最终都满足20m带宽怎么样？4K码率需要达到14M

**Comment by ddgth** [comment]
> 要不就把筛选范围适量扩大 但最终都满足20m带宽怎么样？4K码率需要达到14M

这个还真的保证不了 就算筛选出最优的ip 也不敢保证15min一直都是满速 这个应用比较适合建站
还有 如果富强 建议使用移动带宽 移动带宽走的香港的cf   可能速度上有一定的优势

**Comment by qiuzi** [comment]
可是我电信环境 筛选出来的移动ip我测试一部分不通

**Comment by ddgth** [comment]
> 可是我电信环境 筛选出来的移动ip我测试一部分不通

我的意思是用移动带宽来自选CF IP 
用移动带宽ping 可能会有奇效  移动手机开wifi 电脑连接也可以

**Comment by qiuzi** [comment]
我用actions的

**Comment by ddgth** [comment]
> 我用actions的

可能咱们不在一个频道上
我的意思是你用的哪个网络环境请求的你的源站数据？  改成移动的宽带试试

**Comment by qiuzi** [comment]
好吧 还是希望能区分富强和建站的选项
再次谢谢

**Comment by ddgth** [comment]
> 好吧 还是希望能区分富强和建站的选项
> 再次谢谢

好的。那我下次更新加上一个配置吧。
一个随机选择最优ip 另一个根据下载速度排序根选择最靠前的几个ip
