### ISSUE TITLE
CloudFlareYes 能否放上ipv6地址？

### ISSUE THREAD

**Issue by GeorgeRudd** [ddgth/cf2dns#101]
你好 https://stock.hostmonit.com/CloudFlareYes 这个网页能否加上筛选出的ipv6地址？

**Comment by ddgth** [comment]
已添加，目前联通没有找到合适的IPv6服务器，暂时使用移动的优选IPv6 IP

**Comment by ddgth** [comment]
鼠标放到CFYes导航栏你就可以看到了
