### ISSUE TITLE
腾讯云api2.0下线了，会有影响吗

### ISSUE THREAD

**Issue by prisonervan** [ddgth/cf2dns#110]
北京时间2023年1月1日起对于新增用户已停止旧版本API2.0接口服务，对于存量用户会陆续启动API2.0接口下线。

**Comment by z0z0r4** [comment]
有影响，显然，改了一份
https://github.com/ddgth/cf2dns/pull/112

**Comment by ddgth** [comment]
> 有影响，显然，改了一份 #112

感谢
