### ISSUE TITLE
大佬，服务器证书过期了

### ISSUE THREAD

**Issue by lzyhenniu** [ddgth/cf2dns#123]
![image](https://github.com/ddgth/cf2dns/assets/92658867/4c7d1a93-f2b1-4ddf-a442-0ff475276675)
![image](https://github.com/ddgth/cf2dns/assets/92658867/c1816c42-e428-4dc1-a19d-dca8e5ef0806)

**Comment by ddgth** [comment]
收到 已修复

**Comment by lzyhenniu** [comment]
> 收到已修复

Thanks!
