### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by bz0741** [ddgth/cf2dns#145]
Node.js 16 操作已弃用。请更新以下操作以使用 Node.js 20：actions/checkout@v3、actions/setup-python@v4。有关更多信息，请参阅：https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/。

**Comment by ddgth** [comment]
抱歉 我无法获取错误内容，建议您部署到自己VPS或者使用docker方式部署。
