### ISSUE TITLE
大佬用的那个python版本？

### ISSUE THREAD

**Issue by ixmu** [ddgth/cf2dns#15]
我用的Python 2.7.13
一直提示缺少模块，模块名：parse
实际这个模块已经安装了
Requirement already satisfied: parse in /usr/local/lib/python2.7/dist-packages

**Comment by ddgth** [comment]
> 我用的Python 2.7.13
> 一直提示缺少模块，模块名：parse
> 实际这个模块已经安装了
> Requirement already satisfied: parse in /usr/local/lib/python2.7/dist-packages



> 我用的Python 2.7.13
> 一直提示缺少模块，模块名：parse
> 实际这个模块已经安装了
> Requirement already satisfied: parse in /usr/local/lib/python2.7/dist-packages

代码使用的python3.7版本 你也可以GitHub actions 运行脚本

**Comment by 1362032536** [comment]
尊敬的用户您好：
请问您要询问哪款程序呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ddgth/cf2dns"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月1日(星期五) 下午5:57
收件人:&nbsp;"ddgth/cf2dns"<cf2dns@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [ddgth/cf2dns] 大佬用的那个python版本？ (#15)





  
我用的Python 2.7.13
 一直提示缺少模块，模块名：parse
 实际这个模块已经安装了
 Requirement already satisfied: parse in /usr/local/lib/python2.7/dist-packages
   
我用的Python 2.7.13
 一直提示缺少模块，模块名：parse
 实际这个模块已经安装了
 Requirement already satisfied: parse in /usr/local/lib/python2.7/dist-packages
  
代码使用的python3.7版本 你也可以GitHub actions 运行脚本

**Comment by ixmu** [comment]
> > 我用的Python 2.7.13
> > 一直提示缺少模块，模块名：parse
> > 实际这个模块已经安装了
> > Requirement already satisfied: parse in /usr/local/lib/python2.7/dist-packages
> 
> > 我用的Python 2.7.13
> > 一直提示缺少模块，模块名：parse
> > 实际这个模块已经安装了
> > Requirement already satisfied: parse in /usr/local/lib/python2.7/dist-packages
> 
> 代码使用的python3.7版本 你也可以GitHub actions 运行脚本

使用Action运行也是报错，CHANGE DNS ERROR: ----Time: 2021-01-01 12:57:49----MESSAGE: list indices must be integers or slices, not str
为了不改变它的格式，我专门弄了两个域名

**Comment by ixmu** [comment]
> > 我用的Python 2.7.13
> > 一直提示缺少模块，模块名：parse
> > 实际这个模块已经安装了
> > Requirement already satisfied: parse in /usr/local/lib/python2.7/dist-packages
> 
> > 我用的Python 2.7.13
> > 一直提示缺少模块，模块名：parse
> > 实际这个模块已经安装了
> > Requirement already satisfied: parse in /usr/local/lib/python2.7/dist-packages
> 
> 代码使用的python3.7版本 你也可以GitHub actions 运行脚本

专门装了python3.7，依然是报错
Traceback (most recent call last):
  File "cf2dns.py", line 23, in <module>
    DOMAINS = {{"apnic-ddns.cn": {"ips1": ["CM","CU","CT"]}}}
TypeError: unhashable type: 'dict'

**Comment by ddgth** [comment]
> DOMAINS = {{"apnic-ddns.cn": {"ips1": ["CM","CU","CT"]}}}

DOMAINS = {"apnic-ddns.cn": {"ips1": ["CM","CU","CT"]}}

这样试试吧

**Comment by ixmu** [comment]
> {"apnic-ddns.cn": {"ips1": ["CM","CU","CT"]}}

依然报错
CHANGE DNS ERROR: ----Time: 2021-01-01 13:13:02----MESSAGE: list indices must be integers or slices, not str

**Comment by ddgth** [comment]
> list indices must be integers or slices, not str

最好可以贴出全部的日志信息 
只有这个信息我无法判断是什么问题 大概率是dns第三方授权的问题

或者你可以重新fork 再走一遍流程

**Comment by ixmu** [comment]
好的，我重新fork一个试试
