### ISSUE TITLE
如果要使用actions配置多个域名该怎么写呢

### ISSUE THREAD

**Issue by baizhougod** [ddgth/cf2dns#153]
DOMAINS 需改域名信息，填写时注意不要有换行 例如：{"hostmonit.com": {"@": ["CM","CU","CT"], "shop": ["CM", "CU", "CT"], "stock": ["CM","CU","CT"]},"4096.me": {"@": ["CM","CU","CT"], "vv":["CM","CU","CT"]}}
这里配置两个以上的域名该怎么写呢

**Comment by ddgth** [comment]
4096.me 就是第二个域名
