### ISSUE TITLE
请求增加华为云 

### ISSUE THREAD

**Issue by sw586** [ddgth/cf2dns#19]
华为云 很期待大佬加上

**Comment by nba6648780** [comment]
华为国际版的更好

**Comment by Arronlong** [comment]
https://github.com/Arronlong/py_scripts/tree/master/scripts/cf2dns
自动更新DNS智能解析为CF优质IP
本脚本自ddgth/cf2dns 修改而来，修改内容如下：

添加了DNSPod和华为云的支持（原作者仅提供了阿里云和腾讯云）
添加了多个域名在不同服务商的支持
调整参数名，每个DNS服务商均提供单独的参数（方便后续扩展，接入更多的服务商）
