### ISSUE TITLE
DOMAINS是如何修改的？请大佬赐教！谢谢！

### ISSUE THREAD

**Issue by Jk-z-Box** [ddgth/cf2dns#23]
{"hostmonit.com": {"@": ["CM","CU","CT"], "shop": ["CM", "CU", "CT"], "stock": ["CM","CU","CT"]},"4096.me": {"@": ["CM","CU","CT"], "vv":["CM","CU","CT"]}}
这一段分别代表什么，如何修改，请大佬赐教！谢谢！

**Comment by ddgth** [comment]
hostmonit.com 是顶级域名  @是顶级域名解析 shop stock 是二级域名  4096.me是另一个域名的配置 CM CU CT 分别代表生效的移动 联通 电信 网络
可以设置多个域名

**Comment by cqlp1314** [comment]
购买了试用KEY后，没有获得KEY是什么情况
