### ISSUE TITLE
老哥 错误代码 1

### ISSUE THREAD

**Issue by wache8787** [ddgth/cf2dns#24]
Error: Process completed with exit code 1.
 
这个是什么问题呀

**Comment by ddgth** [comment]
github actions里点击run cf2dns 看看具体的报错信息

**Comment by wache8787** [comment]
Traceback (most recent call last):
  File "cf2dns_actions.py", line 22, in <module>
    DOMAINS = json.loads(os.environ["DOMAINS"])  #{"hostmonit.com": {"@": ["CM","CU","CT"], "shop": ["CM", "CU", "CT"], "stock": ["CM","CU","CT"]},"4096.me": {"@": ["CM","CU","CT"], "vv": ["CM","CU","CT"]}}
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.

**Comment by wache8787** [comment]
具体报错是这些。。完全按你教程走的。

**Comment by ddgth** [comment]
> 具体报错是这些。。完全按你教程走的。

DOMAINS 设置有误 方便的话贴出来 我帮你看看

**Comment by wache8787** [comment]
{"meitong.pro": {"@": ["CM","CU","CT"], "www": ["CM", "CU", "CT"]}}

**Comment by imwbh** [comment]
![erro](https://static01.imgkr.com/temp/7f9b178424a74532946e675fe9e9bb1a.png)
DOMAINS报错，貌似是json转码，不知道怎么解决

**Comment by imwbh** [comment]
> ![https://static01.imgkr.com/temp/7f9b178424a74532946e675fe9e9bb1a.png](https://camo.githubusercontent.com/fc88a55b3d6a1fcc4a59e82c2cc0c7e1697712f6184e747ca6d466b75e8dda4b/68747470733a2f2f73746174696330312e696d676b722e636f6d2f74656d702f37663962313738343234613734353332393436653637356665396539626231612e706e67)
> 
> DOMAINS报错，貌似是json转码，不知道怎么解决
> 我是这么填的
> {"xxxx":{"@":["CM","CU","CT"],"xxx":["CM","CU","CT"],"xxx":["CM","CU","CT"]}}

貌似又好了，真奇怪，早上醒了又自己build成功了

**Comment by ddgth** [comment]
> > ![https://static01.imgkr.com/temp/7f9b178424a74532946e675fe9e9bb1a.png](https://camo.githubusercontent.com/fc88a55b3d6a1fcc4a59e82c2cc0c7e1697712f6184e747ca6d466b75e8dda4b/68747470733a2f2f73746174696330312e696d676b722e636f6d2f74656d702f37663962313738343234613734353332393436653637356665396539626231612e706e67)
> > DOMAINS报错，貌似是json转码，不知道怎么解决
> > 我是这么填的
> > {"xxxx":{"@":["CM","CU","CT"],"xxx":["CM","CU","CT"],"xxx":["CM","CU","CT"]}}
> 
> 貌似又好了，真奇怪，早上醒了又自己build成功了

注意一下密钥填写路径 setting->secrets

**Comment by FengChenHao98** [comment]
我这里也是有事没事就是错误代码1

**Comment by wache8787** [comment]
联系QQ 2333373https://www.meitong.pro/用手机自带浏览器，感谢支持。
