### ISSUE TITLE
请求加上dns.com

### ISSUE THREAD

**Issue by Qingshu1314** [ddgth/cf2dns#29]
😂😂请求大佬加上dns.com

**Comment by ddgth** [comment]
收到 就地过年 春节期间支持一下

**Comment by Qingshu1314** [comment]
😂😂

**Comment by Qingshu1314** [comment]
> 收到就地过年春节期间支持一下

大佬我发现dns.com没有dns.la好用能不能也加下dns.la这是https://www.dns.la/api/doc/
