### ISSUE TITLE
期待大佬适配华为云

### ISSUE THREAD

**Issue by sw586** [ddgth/cf2dns#3]
已购买支持，不错的项目

**Comment by ddgth** [comment]
感谢支持 
华为云已列上日程 敬请期待

**Comment by hietsusama** [comment]
球上 阿里云 / 国际

**Comment by ddgth** [comment]
![Yuki](https://user-images.githubusercontent.com/23150555/99394441-d9354400-2919-11eb-850a-39fbfa7ccd7a.jpg)
不好意思。我家猫周末做了绝育。而且最近工作比较忙 可能要鸽几天。争取月底前上线。

**Comment by sw586** [comment]
大佬 我们一直在等你

**Comment by ddgth** [comment]
> 大佬 我们一直在等你

收到 月底之前

**Comment by ddgth** [comment]
朋友 因为华为云新版的v3SDK中没有DNS的功能 所以

> 球上 阿里云 / 国际

阿里云目前已经支持了 上线仓促 有什么bug直接提issue  感谢
这几天太忙了 阿里国际接口还没看 如果如果参数大差不差 也很快上吧？maybe！！！

**Comment by ddgth** [comment]
> 大佬 我们一直在等你

兄弟 郑重对你道歉 华为接口本月底可能不能上线了  
我看了华为的v3接口 目前暂时不支持DNS 只能用http方式来调  修改的工作量有点大 再加上这几星期工作特别忙 所以要鸽一段时间 不过不会太长 可能下月中旬  maybe！！！

**Comment by sw586** [comment]
没事会一直等你

**Comment by 954187350** [comment]
DNSPOD 1月31日后强制实名，求大佬尽快适配华为云国际版
