### ISSUE TITLE
OMAINS 需改域名信息，能用二级域名吗？

### ISSUE THREAD

**Issue by guohaiping** [ddgth/cf2dns#35]
我想用下cf.******.xyz

采用腾讯云，
运行结果如下：

CHANGE DNS ERROR: ----Time: 2021-03-09 08:42:29----MESSAGE: {'code': 5100, 'message': '(8)服务内部错误，请稍后重试或联系客服人员解决。', 'codeDesc': 'ResourceOpFailed'}

**Comment by guohaiping** [comment]
感谢，可以用了。不过速度比直接用www.v2ex.com的还要慢。

**Comment by ddgth** [comment]
> 感谢，可以用了。不过速度比直接用www.v2ex.com的还要慢。

选择自由
