### ISSUE TITLE
建议对参数进行详细描述

### ISSUE THREAD

**Issue by fengguowudi** [ddgth/cf2dns#36]
{"hostmonit.com": {"@": ["CM","CU","CT"], "shop": ["CM", "CU", "CT"], "stock": ["CM","CU","CT"]},"4096.me": {"@": ["CM","CU","CT"], "vv":["CM","CU","CT"]}}

**Comment by ddgth** [comment]
hostmonit.com为主域名 @、shop、stock 为二级域名
4096.me为另一个主域名  @、vv为第二个主域名的二级域名
