### ISSUE TITLE
服务内部错误，请稍后重试或联系客服人员解决。

### ISSUE THREAD

**Issue by annkoxx** [ddgth/cf2dns#39]
如图
![](https://i0.hdslb.com/bfs/album/f452711a644896720888ee11a11095e2d115a9fa.png)

**Comment by ddgth** [comment]
DNSPod内部报错 仔细看Readme并检查自己的四个Secret参数

**Comment by annkoxx** [comment]
> DNSPod內部報錯仔細看自述文件並檢查自己的四個秘密參數

那这个是因为啥
![](https://i0.hdslb.com/bfs/album/a55ff75953698cbb4a7be10b04d0ca9361454eab.png)

**Comment by ddgth** [comment]
> > DNSPod內部報錯仔細看自述文件並檢查自己的四個秘密參數
> 
> 那这个是因为啥
> ![](https://camo.githubusercontent.com/9dd5f309915ab65d85861e56d2517fdd6b443519fb247a6f1202793e4291c7ba/68747470733a2f2f69302e6864736c622e636f6d2f6266732f616c62756d2f613535666637353935333639386362623461376265313062303464306361393336313435346561622e706e67)

更新下程序再执行下 看下错误是什么
