### ISSUE TITLE
大佬官网1034了

### ISSUE THREAD

**Issue by insoxin** [ddgth/cf2dns#41]
https://developer-forum-online.cdn.bcebos.com/cf408656-305f-4e45-b159-7d529440af12.png

出现问题的是解析到IP为
泛播 Cloudflare172.64.228.*
这一段的网站都会1034
这么多IP负载均衡只有运气特别差才会解析到。
解决办法只要删除A记录为172.64.228.*的解析即可。

加个黑名单区域吧

**Comment by ddgth** [comment]
谢谢提醒
我设定的是每月从 https://www.cloudflare.com/ips-v4 拿一次可用IP  然后每10分钟再在可用IP中 根据不同运营商筛选出优选IP  
本月已经没有这个段了
