### ISSUE TITLE
自动更新优质CF IP已无法正常运行

### ISSUE THREAD

**Issue by aaro-n** [ddgth/cf2dns#45]
在vps或者使用GitHub Actions都无法运行，怀疑是运行环境有改变。

**Comment by ddgth** [comment]
已查出问题并修复
貌似github屏蔽了使用cloudflare的域名，导致代码中调用api出错

**Comment by aaro-n** [comment]
感谢，GitHub Actions版本已经正常，但在VPS上运行不了cf2dns.py。
![截屏2021-04-24 下午4 36 49的副本](https://user-images.githubusercontent.com/45537680/115953036-dae3e300-a51b-11eb-83a2-fd07c438fc4a.png)

**Comment by ddgth** [comment]
> 感谢，GitHub Actions版本已经正常，但在VPS上运行不了cf2dns.py。
> ![截屏2021-04-24 下午4 36 49的副本](https://user-images.githubusercontent.com/45537680/115953036-dae3e300-a51b-11eb-83a2-fd07c438fc4a.png)

缺少依赖了 `pip install -r requirements.txt ` 先执行这条命令安装依赖
然后再运行程序
