### ISSUE TITLE
请求增加dns.com 阿里云

### ISSUE THREAD

**Issue by haig233** [ddgth/cf2dns#5]
RT

**Comment by ddgth** [comment]
收到 月底前先把华为给弄上去吧  看了API  阿里云比华为云 可能在12月前半月上阿里的

**Comment by ddgth** [comment]
http://open.dns.com   帝恩思的API网站打不开 等打开了再看看吧

**Comment by haig233** [comment]
> http://open.dns.com 帝恩思的API网站打不开 等打开了再看看吧

https://www.dns.com/document/api/index.html

**Comment by ddgth** [comment]
> > http://open.dns.com 帝恩思的API网站打不开 等打开了再看看吧
> 
> https://www.dns.com/document/api/index.html
> 
> 地址貌似改了，刚刚开了下，挺全的

好的 这个排在阿里后面吧

**Comment by ddgth** [comment]
阿里云目前已经支持 麻烦多测试一下 上线有点仓促 如果有什么问题直接提issue 或者联系我qq 微信

**Comment by linkala** [comment]
@ddgth 大佬 请问支持国际阿里云吗

**Comment by 2CW** [comment]
> > > http://open.dns.com 帝恩思的API网站打不开 等打开了再看看吧
> > 
> > 
> > https://www.dns.com/document/api/index.html
> > 地址貌似改了，刚刚开了下，挺全的
> 
> 好的 这个排在阿里后面吧

老哥，dns.com提上日程没有？
