### ISSUE TITLE
可以增加境外吗？目前只有cm，cu和ct

### ISSUE THREAD

**Issue by xinmincao** [ddgth/cf2dns#52]

**Comment by ddgth** [comment]
境外走哪个运营商的优选ip呢？
手动加一条境外 走默认不更好吗？

**Comment by weimanmk** [comment]
> 境外走哪个运营商的优选ip呢？
> 手动加一条境外 走默认不更好吗？

如何国外走默认呢

**Comment by ddgth** [comment]
境外和默认功能已经增加 请查看分支版本  境外AB 默认DEF
