### ISSUE TITLE
IP测试策略是什么

### ISSUE THREAD

**Issue by NCDWLQ** [ddgth/cf2dns#57]
RT，请问大佬的这个项目是如何测试出最优IP的，是选ping值低的还是下载速率高的？或是其他策略

**Comment by NCDWLQ** [comment]
感觉部分IP的速度不是很理想

**Comment by ddgth** [comment]
两者皆有 先ping，ping值低 丢包少的会进行下载测速
网络环境错综复杂，并不能去适配每一个人 我只能说对于大部分人是有效的

**Comment by NCDWLQ** [comment]
> 两者皆有 先ping，ping值低 丢包少的会进行下载测速
> 网络环境错综复杂，并不能去适配每一个人 我只能说对于大部分人是有效的

好的
