### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by haig233** [ddgth/cf2dns#6]
建议在解析失败的时候，GitHub设置为运行错误

刚刚发现解析的时候，貌似没连上腾讯的API，出错了，但是GitHub显示的是运行成功

希望可以改进下

**Comment by ddgth** [comment]
> 建议在解析失败的时候，GitHub设置为运行错误
> 
> 刚刚发现解析的时候，貌似没连上腾讯的API，出错了，但是GitHub显示的是运行成功
> 
> 希望可以改进下

不错的建议 我研究下

**Comment by haig233** [comment]
GitHub Actions貌似只要检测到Log有`Error`字符就会自动运行错误了（小声）

**Comment by haig233** [comment]
你可以自己试试
只是猜测
