### ISSUE TITLE
 line 134, in main    for record in ret["data"]["records"]: KeyError: 'data'

### ISSUE THREAD

**Issue by asben** [ddgth/cf2dns#62]
大佬，运行报错，用默认的KEY和试用KEY都不行，ali的解析，怎么解决了

Run python cf2dns_actions.py
  python cf2dns_actions.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.12/x64/lib
    KEY: ***
    DOMAINS: ***
    SECRETID: ***
    SECRETKEY: ***
Traceback (most recent call last):
CHANGE DNS ERROR: ----Time: 2021-11-02 17:53:03----MESSAGE: None
  File "cf2dns_actions.py", line 134, in main
    for record in ret["data"]["records"]:
KeyError: 'data'

**Comment by ddgth** [comment]
这个和用哪个DNS服务商没关系  是因为github连不上我的接口服务器  建议用本地VPS部署使用

**Comment by asben** [comment]
好，谢谢
