### ISSUE TITLE
每次都是添加新解析吗？

### ISSUE THREAD

**Issue by ofdjonf** [ddgth/cf2dns#64]
每次执行脚本都是添加新解析吗？不应该是更换旧解析吗？

**Comment by ddgth** [comment]
看下这个参数AFFECT_NUM 如果当前解析数量没有达到这个参数 那么会新增 否则会更新

**Comment by ofdjonf** [comment]
> 看下这个参数AFFECT_NUM 如果当前解析数量没有达到这个参数，那么会再更新

老哥，这个AFFECT_NUM是不是dnspod里面dns套餐对应的负载均衡条数？还有我在宝塔命令行一直执行不成功，最后用了宝塔里面的Python项目管理器安装了Python3.6.8执行成功了，但是定时任务添加不成功，找不到命令，求教

**Comment by ddgth** [comment]
不一定对应 但要比dnspod负载均衡最大数量要少  我不会用宝塔 linux 定时用crontab windows用计划任务

**Comment by ofdjonf** [comment]
> 特 别支持但不会减少 dnspod 负载均衡最大数量要我用宝塔 linux 定时用 crontab windows 用任务

好的，感谢老哥！最后一个问题，如果购买收费key，它里面是会过滤假墙IP吗？

**Comment by ofdjonf** [comment]
> > 特别支持但不会减少 dnspod 负载均衡最大数量要我用宝塔 linux 定时用 crontab windows 用任务
> 
> 好的，感谢老哥！最后一个问题，如果购买收费钥匙，里面是过滤假墙IP吗？

我看这个免费版，解析上的IP上来直接就是被假墙的。

**Comment by ddgth** [comment]
免费和收费的key都是筛选过可用的ip 但是免费的key是1天前筛选的。
