### ISSUE TITLE
几个参数配置的问题，谢谢

### ISSUE THREAD

**Issue by ofdjonf** [ddgth/cf2dns#65]
大佬，使用key加上fgfw获取到的IP和不带fgfw获取的IP有什么实际区别呢？是加上fgfw获取的IP一定是没被假墙的吗还是什么？
还有，使用fgfw的话，AFFECT_NUM = 填写多少合适？我用的是负载均衡10条的dnspod专业版。
我的域名现在已经被记录，现在每天晚上都会被假墙搞。所以求给个合适的配置方案，谢谢大佬！

**Comment by ddgth** [comment]
> 大佬，使用key加上fgfw获取到的IP和不带fgfw获取的IP有什么实际区别呢？是加上fgfw获取的IP一定是没被假墙的吗还是什么？ 还有，使用fgfw的话，AFFECT_NUM = 填写多少合适？我用的是负载均衡10条的dnspod专业版。 我的域名现在已经被记录，现在每天晚上都会被假墙搞。所以求给个合适的配置方案，谢谢大佬！

1.加不加fgfw都是过滤掉被假墙的IP，只不过使用fgfw方式每次调用接口都会获取到最近筛选出的优选IP且和上次不一样且独享（不会再分配给其他用户），更不容易被假墙，
2.使用fgfw的话不管是不是专业版，每次调用接口每条线路最多只会返回2条记录，所以AFFECT_NUM = 2 更合适
3.如果晚上被假墙 建议使用fgfw方式 并且在晚上缩短调用间隔 TTL设置更短一些

**Comment by ofdjonf** [comment]
> > 大佬，用key外加fgfw获取到的IP和不带fgfw获取的IP有什么实际的区别呢？ AFFECT_NUM = 新建多少？我用的是负载均衡10条的dnspod专业版。
> 
> 1. 不加被假墙的过滤IP，每次调用都会获取到最近使用出的首选IP和上次不一样且唯一（不会再享给其他人）用户），更不容易被假墙， 2.fgfw 什么不管是不是版本，每次调用接口每条线路最多使用一个可能返回2条记录，所以FFECT_NUM = 2更合适 3.如果晚上被假墙建议使用fgfw方式并且在夜间通知间隔TTL设置更短一些


> > 大佬，用key外加fgfw获取到的IP和不带fgfw获取的IP有什么实际的区别呢？ AFFECT_NUM = 新建多少？我用的是负载均衡10条的dnspod专业版。
> 
> 1. 不加被假墙的过滤IP，每次调用都会获取到最近使用出的首选IP和上次不一样且唯一（不会再享给其他人）用户），更不容易被假墙， 2.fgfw 什么不管是不是版本，每次调用接口每条线路最多使用一个可能返回2条记录，所以FFECT_NUM = 2更合适 3.如果晚上被假墙建议使用fgfw方式并且在夜间通知间隔TTL设置更短一些



> > 大佬，用key外加fgfw获取到的IP和不带fgfw获取的IP有什么实际的区别呢？ AFFECT_NUM = 新建多少？我用的是负载均衡10条的dnspod专业版。
> 
> 1. 不加被假墙的过滤IP，每次调用都会获取到最近使用出的首选IP和上次不一样且唯一（不会再享给其他人）用户），更不容易被假墙， 2.fgfw 什么不管是不是版本，每次调用接口每条线路最多使用一个可能返回2条记录，所以FFECT_NUM = 2更合适 3.如果晚上被假墙建议使用fgfw方式并且在夜间通知间隔TTL设置更短一些

那脚本执行时间设置几分钟呢？

**Comment by ofdjonf** [comment]
> > 大佬，用key外加fgfw获取到的IP和不带fgfw获取的IP有什么实际的区别呢？ AFFECT_NUM = 新建多少？我用的是负载均衡10条的dnspod专业版。
> 
> 1. 不加被假墙的过滤IP，每次调用都会获取到最近使用出的首选IP和上次不一样且唯一（不会再享给其他人）用户），更不容易被假墙， 2.fgfw 什么不管是不是版本，每次调用接口每条线路最多使用一个可能返回2条记录，所以FFECT_NUM = 2更合适 3.如果晚上被假墙建议使用fgfw方式并且在夜间通知间隔TTL设置更短一些

那脚本执行时间设置几分钟呢？

**Comment by ddgth** [comment]
> > > 大佬，用key外加fgfw获取到的IP和不带fgfw获取的IP有什么实际的区别呢？ AFFECT_NUM = 新建多少？我用的是负载均衡10条的dnspod专业版。
> > 
> > 
> > 
> > 1. 不加被假墙的过滤IP，每次调用都会获取到最近使用出的首选IP和上次不一样且唯一（不会再享给其他人）用户），更不容易被假墙， 2.fgfw 什么不管是不是版本，每次调用接口每条线路最多使用一个可能返回2条记录，所以FFECT_NUM = 2更合适 3.如果晚上被假墙建议使用fgfw方式并且在夜间通知间隔TTL设置更短一些
> 
> 那脚本执行时间设置几分钟呢？

我觉得这个需要你去试 找到一个临界值，由于本人没被假墙过 所以没办法估算这个间隔时间
PS：TTL的值要小于执行间隔
