### ISSUE TITLE
使用boce测试打开速度大部分移动线路是 *s

### ISSUE THREAD

**Issue by ofdjonf** [ddgth/cf2dns#67]
使用boce.com测试全国打开速度，很多线路测试结果一大片都是超时，000  *s的状态，基本都是移动线路，但是对应的解析 IP没有假墙，能打开。这是啥情况呀？我设置的是tll60秒，AFFECT_NUM = 2，脚本执行时间2分钟，用的是带fgfw的key。一直在被假墙！

**Comment by mayHello** [comment]
我也是，都是移动线路没法用。IP打开正常，网站打不开。

**Comment by ddgth** [comment]
昨晚部分CM节点炸了 现在还没恢复 
如果频繁假墙 建议1min执行一次再试试效果 ttl还是60

**Comment by mayHello** [comment]
> 童年部分CM偶炸了现在还没有恢复 如果你假装墙1分钟再用一次效果建议ttl还是60

不是的，没有假墙的情况，移动线路也用不了。全国打开速度测试，移动基本所有线路都打不开，并且我用代理IP本机测试了，只要链接移动，站点就打不开，测试了很多地区，都一样。大佬，我看你这是混用的吧？没有单独优选线路。

**Comment by mayHello** [comment]
![Screenshot_20211118-171059__01](https://user-images.githubusercontent.com/94573875/142385826-53c977b8-97e8-4d89-bb60-bd5953d3011d.jpg)

![Screenshot_20211118-170843__01](https://user-images.githubusercontent.com/94573875/142385890-66870451-da49-4a95-931c-aaab9bdba052.jpg)
这是我测试别人的一个站点，和我自己的对比，看图2中他的就没有这个问题，所有线路都正常。他肯定用的别的方式。

**Comment by ddgth** [comment]
> ![Screenshot_20211118-171059__01](https://user-images.githubusercontent.com/94573875/142385826-53c977b8-97e8-4d89-bb60-bd5953d3011d.jpg)
> 
> ![Screenshot_20211118-170843__01](https://user-images.githubusercontent.com/94573875/142385890-66870451-da49-4a95-931c-aaab9bdba052.jpg) 这是我测试别人的一个站点，和我自己的对比，看图2中他的就没有这个问题，所有线路都正常。他肯定用的别的方式。

混用是什么意思？ 光移动我都买了六台机了 昨晚down了2台

**Comment by ddgth** [comment]
> ![Screenshot_20211118-171059__01](https://user-images.githubusercontent.com/94573875/142385826-53c977b8-97e8-4d89-bb60-bd5953d3011d.jpg)
> 
> ![Screenshot_20211118-170843__01](https://user-images.githubusercontent.com/94573875/142385890-66870451-da49-4a95-931c-aaab9bdba052.jpg) 这是我测试别人的一个站点，和我自己的对比，看图2中他的就没有这个问题，所有线路都正常。他肯定用的别的方式。

好好想想是不是自己域名被移送真墙了

**Comment by mayHello** [comment]
> > ![截图_20211118-171059__01](https://user-images.githubusercontent.com/94573875/142385826-53c977b8-97e8-4d89-bb60-bd5953d3011d.jpg)
> > ![截图_20211118-170843__01](https://user-images.githubusercontent.com/94573875/142385890-66870451-da49-4a95-931c-aaab9bdba052.jpg) 这是我测试别人的一个站点，和我自己的对比，看图2中他的就没有这个问题，所有的线路都正常。他用的另一种方式。
> 
> 好想是不是自己的域名被移送真墙了

不是吧，那电信节点和联通，一切正常，速度还很快。就移动打不开。

**Comment by ddgth** [comment]
> > > ![截图_20211118-171059__01](https://user-images.githubusercontent.com/94573875/142385826-53c977b8-97e8-4d89-bb60-bd5953d3011d.jpg)
> > > ![截图_20211118-170843__01](https://user-images.githubusercontent.com/94573875/142385890-66870451-da49-4a95-931c-aaab9bdba052.jpg) 这是我测试别人的一个站点，和我自己的对比，看图2中他的就没有这个问题，所有的线路都正常。他用的另一种方式。
> > 
> > 
> > 好想是不是自己的域名被移送真墙了
> 
> 不是吧，那电信节点和联通，一切正常，速度还很快。就移动打不开。

如果你玩hostloc的话 你就知道什么情况了
