### ISSUE TITLE
可以增加ServerChan

### ISSUE THREAD

**Issue by haig233** [ddgth/cf2dns#8]
可以考虑增加ServerChan作为可选功能，无论成功与否，微信推送信息，以便了解解析情况

**Comment by ddgth** [comment]
> 可以考虑增加ServerChan作为可选功能，无论成功与否，微信推送信息，以便了解解析情况

说实话 只要能运行成功2次 基本问题不大 我现在很想知道 阿里云dns怎么把邮件提醒去掉 现在只要删除dns记录 就一堆邮件
