### ISSUE TITLE
因为这两天`*.workers.dev`炸了, 104开头的IP 均不能使用

### ISSUE THREAD

**Issue by DemoorBug** [ddgth/cf2dns#88]
请问怎么屏蔽掉104开头的IP

**Comment by ddgth** [comment]
每一个ip都是国内服务器刚刚筛选出来的 保证可以正常使用的  104开头的ip并没有问题  本人网站解析104开头的CF IP 拨测三网都正常
可能你本地是联通宽带， 近期联通-CF链路可能出问题了 不太稳定

**Comment by DemoorBug** [comment]
> 

https://github.com/XIU2/CloudflareSpeedTest/issues/208
https://github.com/XIU2/CloudflareSpeedTest/issues/205#issuecomment-1122001544

确实是有这个问题,现在很需要这个屏蔽IP的功能, 如果修改源码可以的话,麻烦告知一下,我自己改改

**Comment by DemoorBug** [comment]
我的宽带是移动, 目前就104开头的有问题

**Comment by DemoorBug** [comment]
好了,谢谢了

**Comment by pzghost** [comment]
将 `response = http.request('POST','https://api.hostmonit.com/get_optimization_ip',body=data, headers=headers)` 改成了 `response = http.request('POST','https://api.hostmonit.com/get_optimization_ip_without104',body=data, headers=headers)`, 运行了几次，移动没分配到 104 打头的 IP。

**Comment by DemoorBug** [comment]
> 

今天又不行了
```
Traceback (most recent call last):
CHANGE DNS SUCCESS: ----Time: 2022-05-11 09:06:37----DOMAIN: demoorbug.gg----SUBDOMAIN: @----RECORDLINE: 移动----RECORDID: 1118700973----VALUE: 104.24.202.55
CHANGE DNS SUCCESS: ----Time: 2022-05-11 09:06:39----DOMAIN: demoorbug.gg----SUBDOMAIN: @----RECORDLINE: 移动----RECORDID: 1118700954----VALUE: 104.21.68.242
CHANGE DNS SUCCESS: ----Time: 2022-05-11 09:06:40----DOMAIN: demoorbug.gg----SUBDOMAIN: @----RECORDLINE: 联通----RECORDID: 1118701025----VALUE: 198.41.222.255
CHANGE DNS SUCCESS: ----Time: 2022-05-11 09:06:42----DOMAIN: demoorbug.gg----SUBDOMAIN: @----RECORDLINE: 联通----RECORDID: 1118701000----VALUE: 104.19.14.114
CHANGE DNS SUCCESS: ----Time: 2022-05-11 09:06:43----DOMAIN: demoorbug.gg----SUBDOMAIN: @----RECORDLINE: 电信----RECORDID: 1118701074----VALUE: 104.21.8.51
CHANGE DNS SUCCESS: ----Time: 2022-05-11 09:06:45----DOMAIN: demoorbug.gg----SUBDOMAIN: @----
```
可以给我一个接口,把联通电信移动所有104开头的屏蔽吗

**Comment by ddgth** [comment]
将cf2dns.py 中52行 get_optimization_ip 改为 get_optimization_ip_without104
修改完后移动联通电信都不会出现104开头的ip  请检查你的代码是否修改

**Comment by ddgth** [comment]
> 将 `response = http.request('POST','https://api.hostmonit.com/get_optimization_ip',body=data, headers=headers)` 改成了 `response = http.request('POST','https://api.hostmonit.com/get_optimization_ip_without104',body=data, headers=headers)`, 运行了几次，移动没分配到 104 打头的 IP。

更改后就是要屏蔽掉104开头的ip  没分配到属于正常情况

**Comment by DemoorBug** [comment]
> 将cf2dns.py 中52行 get_optimization_ip 改为 get_optimization_ip_without104 修改完后移动联通电信都不会出现104开头的ip 请检查你的代码是否修改
[
](https://github.com/DemoorBug/cf2dns/blob/fa06f6e90f5a7b456c2f464dfbf90f39d3338559/cf2dns.py#L52)

又运行了两次, 还是一样, 很随机

**Comment by DemoorBug** [comment]
> 将cf2dns.py 中52行 get_optimization_ip 改为 get_optimization_ip_without104 修改完后移动联通电信都不会出现104开头的ip 请检查你的代码是否修改

https://github.com/DemoorBug/cf2dns/blob/fa06f6e90f5a7b456c2f464dfbf90f39d3338559/cf2dns.py#L52
又运行了两次, 还是会随机出现104开头的IP,并没有屏蔽掉, 我想要一个屏蔽所有104开头IP的接口,比如说联通电信都屏蔽了, IP少一点无所谓

**Comment by DemoorBug** [comment]
<img width="909" alt="截屏2022-05-11 下午7 11 31" src="https://user-images.githubusercontent.com/18387615/167836349-e581cde3-bbf7-4aa2-8440-ae626f1f707f.png">

**Comment by DemoorBug** [comment]
> 将cf2dns.py 中52行 get_optimization_ip 改为 get_optimization_ip_without104 修改完后移动联通电信都不会出现104开头的ip 请检查你的代码是否修改

https://github.com/DemoorBug/cf2dns/blob/fa06f6e90f5a7b456c2f464dfbf90f39d3338559/cf2dns.py#L52
修改了啊, 难道我改的不对吗

**Comment by ddgth** [comment]
> > 将cf2dns.py 中52行 get_optimization_ip 改为 get_optimization_ip_without104 修改完后移动联通电信都不会出现104开头的ip 请检查你的代码是否修改
> 
> https://github.com/DemoorBug/cf2dns/blob/fa06f6e90f5a7b456c2f464dfbf90f39d3338559/cf2dns.py#L52 修改了啊, 难道我改的不对吗

修改的没问题 ， 本人再次验证，代码没问题，没有新增104IP的记录 请检查执行的脚本是否有问题。

**Comment by qiuzi** [comment]
这几天深圳地区连接真的很拉跨，手动筛选也保不住一天。ipv6有进展了吗？

**Comment by DemoorBug** [comment]
> > > 将cf2dns.py 中52行 get_optimization_ip 改为 get_optimization_ip_without104 修改完后移动联通电信都不会出现104开头的ip 请检查你的代码是否修改
> > 
> > 
> > https://github.com/DemoorBug/cf2dns/blob/fa06f6e90f5a7b456c2f464dfbf90f39d3338559/cf2dns.py#L52 修改了啊, 难道我改的不对吗
> 
> GitHub Actions 运行的话，修改 cf2dns_actions.py

好吧，原来要改这里

**Comment by DemoorBug** [comment]
@ddgth 还有个问题,https://hostmonit.com/manually-select-ip/ 里面用到CloudFlare Partner来实现CNAME接入,不过目前好像官方已经禁用了这个, 目前我找到的是用CloudFlare Saas来替代此方案, 但是如果要加速例如github page,好像不行哎

**Comment by DemoorBug** [comment]
@ddgth 还有个问题,https://hostmonit.com/manually-select-ip/ 里面用到CloudFlare Partner来实现CNAME接入,不过目前官方已经禁用了这个, 我找到的是用CloudFlare Saas来替代此方案, 但是如果要加速例如github page,好像不行哎, 还有别的方法吗?

**Comment by DemoorBug** [comment]
@ddgth 还有个问题,https://hostmonit.com/manually-select-ip/ 里面用到CloudFlare Partner来实现CNAME接入,不过目前好像官方已经禁用了这个, 目前我找到的是用CloudFlare Saas来替代此方案. 但是如果要加速例如github page 的话, 利用这种Saas就会报404错误, 因为GitHub page只能绑定一个域名,而使用Sass必须经过两个不同的域名才行, 还有其他解决方法吗?

**Comment by DemoorBug** [comment]
@ddgth 还有个问题,https://hostmonit.com/manually-select-ip/ 里面用到CloudFlare Partner来实现CNAME接入,不过目前好像官方已经禁用了这个, 我找到的是用CloudFlare Saas来替代此方案. 但是如果要加速例如github page 的话, 利用Saas就会报404错误, 因为GitHub page只能绑定一个域名,而使用Sass必须经过两个不同的域名才行, 还有其他解决方法吗?

**Comment by ddgth** [comment]
> @ddgth 还有个问题,https://hostmonit.com/manually-select-ip/ 里面用到CloudFlare Partner来实现CNAME接入,不过目前好像官方已经禁用了这个, 我找到的是用CloudFlare Saas来替代此方案. 但是如果要加速例如github page 的话, 利用Saas就会报404错误, 因为GitHub page只能绑定一个域名,而使用Sass必须经过两个不同的域名才行, 还有其他解决方法吗?

不确定ION WP还能不能使用了 可以了解一下

**Comment by KimiBear** [comment]
这几天选出的IP 都无法使用IPV4 ipv6都一样 是炸了吗？





------------------ 原始邮件 ------------------
发件人: qiuzi ***@***.***&gt;
发送时间: 2022年5月11日 21:19
收件人: ddgth/cf2dns ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ddgth/cf2dns] 因为这两天`*.workers.dev`炸了, 104开头的IP 均不能使用 (Issue #88)






这几天深圳地区连接真的很拉跨，手动筛选也保不住一天。ipv6有进展了吗？
