### ISSUE TITLE
正常运行出现重复记录

### ISSUE THREAD

**Issue by am-abudu** [ddgth/cf2dns#9]
正常运行action，dnspod却出现了重复的解析记录，没有删除老的解析而是直接添加了新解析

**Comment by ddgth** [comment]
重复的解析记录是指？ 解析的线路 值都相同吗？ 举个例子 最好配一个dnspod解析图

**Comment by am-abudu** [comment]
就是新添加解析不会删除原有的解析，同一个线路出现两个不同的值，形成类似负载均衡

**Comment by ddgth** [comment]
> 就是新添加解析不会删除原有的解析，同一个线路出现两个不同的值，形成类似负载均衡

因为免费版的DNSPod想通的线路最多可以解析两条记录  所以每次运行程序 都会更新相同线路的两条记录 如果还有疑问 麻烦你最好能够贴下图 把域名打下码

**Comment by am-abudu** [comment]
![Uploading 869AEAD6-9C38-4627-B8D8-9821D804D801.jpeg…]()

**Comment by ddgth** [comment]
> ![DC49AC95-5DE0-4BC2-B21F-891DDFA88BD6](https://user-images.githubusercontent.com/51912589/100517489-c4806800-31c5-11eb-850a-bb69dfe003ef.jpeg)
> 我是那个一块钱的个人专业版，是不是这个原因
 因为个人专业版每个线路可以有10条解析记录  所以你将代码中AFFECT_NUM 这个参数改成10 试一下 
这个我没有测试 麻烦使用时有什么问题请及时反馈

**Comment by am-abudu** [comment]
好家伙改完给我添加了十条dns，不行啊

**Comment by ddgth** [comment]
> 好家伙改完给我添加了十条dns，不行啊

10条就对了 等下次运行看看之前的10条记录会不会改变吧

**Comment by am-abudu** [comment]
我还以为每个线路只有一个ip呢，打扰了:lol
