### ISSUE TITLE
action 最后出现这个报错

### ISSUE THREAD

**Issue by emmmnaadada** [ddgth/cf2dns#90]
![image](https://user-images.githubusercontent.com/101549560/168951348-2d02c684-3720-4c18-b879-0b7236eb7e86.png)

**Comment by ddgth** [comment]
点击看具体报错信息，不过还是推荐部署到自己的VPS上

**Comment by emmmnaadada** [comment]
> 点击看具体报错信息，不过还是推荐部署到自己的VPS上
你看下
![Uploading image.png…]()

**Comment by emmmnaadada** [comment]
> 点击看具体报错信息，不过还是推荐部署到自己的VPS上
你看下
![Uploading image.png…]()

**Comment by emmmnaadada** [comment]
> 点击看具体报错信息，不过还是推荐部署到自己的VPS上

![image](https://user-images.githubusercontent.com/101549560/168952424-0b5e214a-1c14-411c-bad2-af3ea0b2d647.png)

**Comment by ddgth** [comment]
> > 点击看具体报错信息，不过还是推荐部署到自己的VPS上
> 
> ![image](https://user-images.githubusercontent.com/101549560/168952424-0b5e214a-1c14-411c-bad2-af3ea0b2d647.png)

方法二：GitHub Actions 运行,第四步做了吗？ 还是推荐部署到自己的VPS上

**Comment by emmmnaadada** [comment]
> > > 点击看具体报错信息，不过还是推荐部署到自己的VPS上
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/101549560/168952424-0b5e214a-1c14-411c-bad2-af3ea0b2d647.png)
> 
> 方法二：GitHub Actions 运行,第四步做了吗？ 还是推荐部署到自己的VPS上

![image](https://user-images.githubusercontent.com/101549560/168953661-bf7c154f-7426-425c-a816-c1650a7f32e4.png)
zhelk 第四步都修改了
