### ISSUE TITLE
本地运行报错与腾讯云API问题

### ISSUE THREAD

**Issue by InoryS** [ddgth/cf2dns#91]
本地运行出现
```
Traceback (most recent call last):
  File "/cf2dns/cf.py", line 13, in <module>
    from dns.qCloud import QcloudApi
ModuleNotFoundError: No module named 'dns.qCloud'
```

已经反复确认过依赖安装

如果用 Github Action 则提示
`Exception: {'code': 4102, 'message': '[request id:]you are not authorized to perform operation (cns:RecordList)\nresource (*) has no permission\n', 'codeDesc': 'SecretidNotAuthAccessResource'}`

已经在腾讯云授权了 DNSPod 全读写访问权限。
看了眼腾讯文档，这个 API 已经过期了，要求使用 API 3.0。
希望可以进行维护，谢谢。

**Comment by ddgth** [comment]
重新pull代码再试一次
